### ISSUE TITLE
Desktop wall Issue

### ISSUE THREAD

**Issue by karambaq** [olzraiti/dotfiles#10]
./desktop_wall switch north                                      
Traceback (most recent call last):
  File "./desktop_wall", line 46, in <module>
    path = os.environ.get('BSPWM_SCRIPTS_DIR') + "/get_focused"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by olzraiti** [comment]
You'll need to set $BSPWM_SCRIPTS_DIR environment variable. It should point to the path where the bspwm scripts are. I initialize the variable in `.profile`.

**Comment by karambaq** [comment]
@olzraiti Thanks, that's help. But I have another issue, can I post in this thread or create a new one?

**Comment by olzraiti** [comment]
Either way is fine. :-)

**Comment by karambaq** [comment]
@olzraiti 
`
/home/maxq/rice/bspwm_scripts/get_focused: line 2: jq: command not found
unexpected desktop name: [b''] (call 'desktop-wall init')
`

**Comment by olzraiti** [comment]
You'll need to install `jq`.

**Comment by karambaq** [comment]
@olzraiti Oh, stupid me.
It's ok now. But I still can't see my desktops layout like in your gif on reddit, I tried to execute every script, no errors, but no work. How can I found what's wrong?

**Comment by olzraiti** [comment]
See if the desktops were initialized correctly with `bspc query -D --names`. For 3x2 grid the name should be:
```
1-1                                                                                                                                                        
2-1
3-1
1-2
2-2
3-2
```

**Comment by karambaq** [comment]
@olzraiti Yes it is.

**Comment by olzraiti** [comment]
Are you using the `desktop_wall` script for navigation? Go to desktop `1-1` (you can check your current desktop with `bspc query -D -d --names`). Then switch the desktop with `$BSPWM_SCRIPTS_DIR/desktop_wall switch east`. Check your current desktop again - you should be in `2-1`.

**Comment by karambaq** [comment]
@olzraiti Yes, It works fine. But I can't see notification about changing of workspace.

**Comment by olzraiti** [comment]
`bin/notify_focused_desktop` fires the notification - but it works only on my custom notification system (`bar_notifyd`). You could edit `notify_focused_desktop` to send the notification with `notify-send` instead of my custom `notify`, but that wouldn't really work since the default notification manager doesn't support multiline notifications. I trigger `notify_focused_desktop` after changing the desktop in `sxhkdrc`.

**Comment by karambaq** [comment]
I copied all from you bin/ folder and now when I try start bar_notifyd:
`cat: /tmp/xrandr_output: Folder doesn't exist
/usr/local/bin/bar_notifyd: строка 98: inotifywait: command not found
`

**Comment by olzraiti** [comment]
`bar_notifyd` assumes that xrandr output is found at `/tmp/xrandr_output` (I cache it there in my `.xinitrc` because it takes quite long for xrandr to output). You can either also cache xrandr output to `/tmp/xrandr_output` or edit `bar_notifyd` to use xrandr output directly.

Make sure you have installed `inotifywait`.

**Comment by karambaq** [comment]
It looks like sind is out of date.

**Comment by olzraiti** [comment]
Unfortunately, yes. You can get the sources here and build it manually (https://github.com/olzraiti/simplenotificationdaemon.)

**Comment by olzraiti** [comment]
Though you don't need sind for using `bar_notifyd`! You can send notifications to `bar_notifyd` with `notify`. Sind just allows using the `bar_notify` notification system for freedesktop notifications.

**Comment by karambaq** [comment]
@olzraiti Looks like it works. But is seems like empty notification in the top left corner.
![screenshot-2017-07-22_19 53 02](https://user-images.githubusercontent.com/14233969/28493031-7deedb20-6f17-11e7-9277-36184294890c.png)

**Comment by olzraiti** [comment]
Is it there all the time? Do the notifications work otherwise?

**Comment by karambaq** [comment]
@olzraiti Only when I change workspace. May be I need to initialize icons? But here?

**Comment by olzraiti** [comment]
I'm guessing parsing `xrandr` output is failing. You can debug `bar_notify` by `echo`ing some of the values parsed from `xrandr` output.

I initialize icons in `.profile`. You can test whether the notifications work regardless of icons by  `notify this is a test`
