### ISSUE TITLE
Dropdown and pull-up terminals

### ISSUE THREAD

**Issue by FerdinK** [olzraiti/dotfiles#12]
Hey man,

I don't know if you're still using this config, but I tried to use your "quakify", "spawn_quakified", etc. scripts , but it just gives me 3 errors and spawns a "normal" terminal.

Here are the messages I get when I run `spawn_quakified -g -d top urxvt`:
`cat: /dev/shm/quakify/names_to_wins/quakify_global_top_quakedurxvt: No such file or directory`
`ls: cannot access '/dev/shm/quakify/wins_to_names/27262986': No such file or directory`
`/home/frost/.bin/quakify/quakify: line 318: / 3: syntax error: operand expected (error token is "/ 3")`

I've been trying to figure out what's going on, but with no success.

Thanks !

**Comment by olzraiti** [comment]
`quakify` assumes that xrandr output is found at `/dev/shm/xrandr_output` (I cache it there in my .xinitrc because it takes quite long for xrandr to output). You can either also cache xrandr output to '/dev/shm/xrandr_output' or edit the script to use xrandr output directly (line 302)

**Comment by FerdinK** [comment]
The file `/dev/shm/xrandr_output` exists, I saw it was needed by your scripts so I cached xrandr ouput from my autostart script

**Comment by FerdinK** [comment]
I think I found the problem, by looking at you scripts and the xrandr ouput, it appears that my laptops uses `HDMI-0` as primary monitor instead of `DP-0`, so when it tries to get the `display_height` and `display_width̀` they are set to nothing, because of the monitor problem !

Thanks anyway, problem solved !
