### ISSUE TITLE
"sind" command

### ISSUE THREAD

**Issue by kahrkunne** [olzraiti/dotfiles#2]
In bin/notifyd, there's a use of a command called "sind". Where is it from? I can't find it anywhere.

**Comment by olzraiti** [comment]
It's this: https://github.com/htylo/simplenotifydaemon. Also available on the AUR as `sind-git` if you happen to be using Linux Arch. It simply outputs freedesktop notifications which I bind to my custom notification system in the script.

**Comment by kahrkunne** [comment]
Thanks.
