### ISSUE TITLE
workspace indicator

### ISSUE THREAD

**Issue by lampenhauser** [olzraiti/dotfiles#7]
Hi,

I really like your setup and I am trying to do something similar with i3. I am a bit new to all this though and I couldn't figure out which program is doing the notification that shows you which workplace you are on. Could you tell me?

**Comment by olzraiti** [comment]
Sure, it's bin/notify_focused_desktop. It uses bspwm utilities to find out the active workspace & filled workspaces, so you'll need to edit it. My custom notification system uses `;` as a line demiliter - your notification manager won't probably handle the line break.

**Comment by lampenhauser** [comment]
Thanks, so all your notifications are done by your own scripts?

**Comment by olzraiti** [comment]
That's right. The notification script is bin/bar_notifyd.
