### ISSUE TITLE
Dropdown Terminal Integration

### ISSUE THREAD

**Issue by 1337Nerd** [olzraiti/dotfiles#8]
How would I use your existing code to make my own dropdown terminal? So far I've copied your quakify, quake_terminal, and get_name programs, but it gives me an error message.

**Comment by olzraiti** [comment]
`quakify` will make any window act like a dropdown window. `bin/workspace_terminal` creates a new terminal and uses `quakify` to make it a dropdown window.

The setup works only in BSPWM - if you use something else, you'll need to edit the parts in quakify scripts that use bspwm utils.
